ARG DEBIAN_DISTRO
FROM bearstech/debian:${DEBIAN_DISTRO}

ARG RUBY_VERSION

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
            ruby \
            ruby${RUBY_VERSION} \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  gem install --version=1.13.6 bundler \
    &&  gem cleanup all
