ARG DEBIAN_DISTRO
FROM bearstech/debian:${DEBIAN_DISTRO}

ARG RUBY_VERSION

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                  build-essential \
                  bundler \
                  git \
                  ruby \
                  ruby${RUBY_VERSION} \
                  ruby${RUBY_VERSION}-dev \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*
