FROM bearstech/debian:stretch

RUN apt-get update && \
    apt-get install -y \
	build-essential \
	bundler \
        git \
        ruby2.3 \
	ruby2.3-dev \
    && apt-get install -y ruby \
    && rm -rf /var/lib/apt/lists/*
