FROM bearstech/ruby:2.4

WORKDIR /sinatra
ENV SINATRA_VERSION 2.0.0
ENV BUNDLE_PATH /vendor
ENV BUNDLE_BIN /usr/local/bin

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN set -eux \
    &&  echo "source 'https://rubygems.org'" | tee Gemfile \
    &&  echo "gem \"sinatra\", \"= $SINATRA_VERSION\"" | tee -a Gemfile \
    &&  bundle config set path 'vendor' \
    &&  bundle install --binstubs=/usr/local/bin

SHELL ["/bin/sh", "-c"]
EXPOSE 4567

# web page should be /sinatra/web.rb, COPY it, or mount it.
CMD ["bundle", "exec", "ruby", "web.rb"]

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-ruby \
    org.opencontainers.image.source=https://github.com/factorysh/docker-ruby/blob/${GIT_VERSION}/Dockerfile.sinatra-dev
