ARG RUBY_FROM
FROM bearstech/${RUBY_FROM}

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                    build-essential \
                    ca-certificates \
                    git \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*
