ARG RUBY_FROM_TAG
FROM bearstech/ruby:${RUBY_FROM_TAG}

RUN set -eux \
    &&  export http_proxy=${HTTP_PROXY} \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                    build-essential \
                    ca-certificates \
                    git \
                     libgmp-dev \
                    libpq-dev \
                    lsb-release \
    && if [ "$(lsb_release -cs)" = "buster" ]; then \
           apt-get install -y --no-install-recommends \
                    libmariadb-dev \
       ; fi \
    && if [ "$(lsb_release -cs)" = "stretch" ]; then \
           apt-get install -y --no-install-recommends \
                    default-libmysqlclient-dev \
                    libmariadb-dev \
       ; fi \
    && if [ "$(lsb_release -cs)" = "jessie" ]; then \
           apt-get install -y --no-install-recommends \
                    libmysqlclient-dev \
       ; fi \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

RUN gem install rake -v 13.0.3 && gem install rake-compiler -v 1.1.1

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL com.bearstech.image.revision_date=${GIT_DATE}

LABEL org.opencontainers.image.authors=Bearstech

LABEL org.opencontainers.image.revision=${GIT_VERSION}
LABEL org.opencontainers.image.created=${BUILD_DATE}

LABEL org.opencontainers.image.url=https://github.com/factorysh/docker-ruby
LABEL org.opencontainers.image.source=https://github.com/factorysh/docker-ruby/blob/${GIT_VERSION}/Dockerfile.ruby-install-dev
