ARG DEBIAN_DISTRO
FROM bearstech/debian:${DEBIAN_DISTRO}

ARG DEBIAN_DISTRO
ARG RUBY_VERSION

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                  build-essential \
                  bundler \
                  git \
                  libgmp-dev \
                  libpq-dev \
                  ruby \
                  ruby${RUBY_VERSION} \
                  ruby${RUBY_VERSION}-dev \
                  default-libmysqlclient-dev \
                  libmariadb-dev \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-ruby \
    org.opencontainers.image.source=https://github.com/factorysh/docker-ruby/blob/${GIT_VERSION}/Dockerfile.apt-dev
