FROM bearstech/ruby:2.4

WORKDIR /sinatra
ENV SINATRA_VERSION 2.0.0

RUN echo "source 'https://rubygems.org'" > Gemfile && \
    echo "gem \"sinatra\", \"= $SINATRA_VERSION\"" >> Gemfile && \
    bundle install --binstubs=/usr/local/bin --path=/vendor

ENV BUNDLE_PATH /vendor
ENV BUNDLE_BIN /usr/local/bin
EXPOSE 4567
