FROM bearstech/ruby:2.4

WORKDIR /sinatra
ENV SINATRA_VERSION 2.0.0
ENV BUNDLE_PATH /vendor
ENV BUNDLE_BIN /usr/local/bin

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN set -eux \
    &&  echo "source 'https://rubygems.org'" | tee Gemfile \
    &&  echo "gem \"sinatra\", \"= $SINATRA_VERSION\"" | tee -a Gemfile \
    &&  bundle install --binstubs=/usr/local/bin --path=/vendor

SHELL ["/bin/sh", "-c"]
EXPOSE 4567

# web page should be /sinatra/web.rb, COPY it, or mount it.
CMD ["bundle", "exec", "ruby", "web.rb"]
