ARG DEBIAN_DISTRO
FROM bearstech/debian:${DEBIAN_DISTRO}

ARG DEBIAN_DISTRO
ARG RUBY_VERSION

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                  build-essential \
                  bundler \
                  git \
                  libgmp-dev \
                  libpq-dev \
                  ruby \
                  ruby${RUBY_VERSION} \
                  ruby${RUBY_VERSION}-dev \
                  default-libmysqlclient-dev \
                  libmariadb-dev \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

ARG GIT_VERSION
LABEL com.bearstech.source.ruby=https://github.com/factorysh/docker-ruby/commit/${GIT_VERSION}

ARG GIT_DATE
LABEL com.bearstech.date.ruby=${GIT_DATE}
