---

version: "3"

services:
    pg:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: test
            POSTGRES_DB: demo

    maria:
        image: mariadb:10.1
        environment:
            MYSQL_ROOT_PASSWORD: s3cr3t
            MYSQL_DATABASE: demo
            MYSQL_USER: test
            MYSQL_PASSWORD: example

    client:
        build:
            context: .
            args:
                RUBY_VERSION: ${RUBY_VERSION}
        links:
            - pg
            - maria
        volumes:
            - .:/test
        working_dir: /test
        tty: true
        command: ./bin/goss -g test.yml validate --format documentation
